# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-31 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='totalAns',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='totalQues',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
