# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-31 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='q1selected',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='q2selected',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='q3selected',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='q4selected',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
